# Generated by Django 3.1.dev20200225131619 on 2020-03-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilePage', '0002_auto_20200312_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
            ],
        ),
    ]
