# Generated by Django 3.1 on 2020-03-23 00:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilePage', '0002_auto_20200312_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cartItems',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=[], size=None),
        ),
    ]
