# Generated by Django 3.1 on 2020-03-23 00:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilePage', '0003_account_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cartItems',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, size=None),
        ),
    ]
