# Generated by Django 3.1.dev20200225131619 on 2020-03-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilePage', '0003_imagelinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelinks',
            name='link',
            field=models.TextField(default='AAAAAAAAA'),
        ),
    ]
