# Generated by Django 3.1.dev20200225131619 on 2020-03-22 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilePage', '0004_auto_20200321_2140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageLinks',
            new_name='ImageLink',
        ),
    ]
