# Generated by Django 3.1.dev20200225131619 on 2020-03-23 01:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilePage', '0005_auto_20200321_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelink',
            name='creator',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='imagelink',
            name='desciption',
            field=models.TextField(default='No Description Provided'),
        ),
        migrations.AddField(
            model_name='imagelink',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=25), blank=True, default=['oh no spaghet', 'test'], size=None),
            preserve_default=False,
        ),
    ]
