# Generated by Django 3.1.dev20200225131619 on 2020-03-23 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilePage', '0006_auto_20200322_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagelink',
            old_name='desciption',
            new_name='description',
        ),
    ]
