# Generated by Django 3.1 on 2020-03-23 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilePage', '0004_auto_20200323_0009'),
        ('ProfilePage', '0007_auto_20200322_1844'),
    ]

    operations = [
    ]
