# Generated by Django 3.1 on 2020-03-23 22:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilePage', '0008_merge_20200323_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='purchased',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, size=None),
        ),
    ]
