# Generated by Django 3.1 on 2020-03-28 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilePage', '0010_imagelink_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelink',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
