# Generated by Django 3.1.dev20200225131619 on 2020-04-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilePage', '0011_imagelink_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelink',
            name='username',
            field=models.TextField(default='Its Over I Have The High Ground'),
        ),
    ]
