# Generated by Django 3.1 on 2020-04-20 22:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilePage', '0011_imagelink_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='viewed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='imagelink',
            name='blurred',
            field=models.TextField(default='http://wallpaperstock.net/wallpapers/thumbs1/42657hd.jpg'),
        ),
    ]
