# Generated by Django 3.1 on 2020-05-02 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilePage', '0012_imagelink_username'),
        ('ProfilePage', '0012_auto_20200420_2212'),
    ]

    operations = [
    ]
