# Generated by Django 3.1 on 2020-05-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilePage', '0013_merge_20200502_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelink',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
