# Generated by Django 3.0.5 on 2020-05-02 23:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilePage', '0013_merge_20200502_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='followers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='account',
            name='following',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, size=None),
        ),
    ]
